ARG BASE
FROM $BASE

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBEMAIL=jenkins@openwebrx.de
ENV DEBFULLNAME="OpenWebRX Jenkins"

RUN echo 'Acquire::Retries "3";' > /etc/apt/apt.conf.d/80-retries && \
    apt-get update && \
    apt-get install -y --no-upgrade --no-install-recommends wget gpg apt-transport-https ca-certificates && \
    wget -O - https://repo.openwebrx.de/debian/key.gpg.txt | gpg --dearmor -o /usr/share/keyrings/openwebrx.gpg && \
    if grep -q "Ubuntu" /etc/os-release; then \
        echo "deb [signed-by=/usr/share/keyrings/openwebrx.gpg] https://repo.openwebrx.de/ubuntu/ jammy main" > /etc/apt/sources.list.d/openwebrx.list; \
    else \
        echo "deb [signed-by=/usr/share/keyrings/openwebrx.gpg] https://repo.openwebrx.de/debian/ bullseye main" > /etc/apt/sources.list.d/openwebrx.list; \
    fi && \
    apt-get update && \
    apt-get install -y --no-upgrade --no-install-recommends \
      cmake build-essential debsigs git devscripts lintian dh-python python3-all python3-setuptools libpython3-dev \
      libfftw3-dev librtlsdr-dev libsoapysdr-dev soapysdr-tools netcat-traditional git-buildpackage libitpp-dev \
      libsndfile1-dev portaudio19-dev help2man pkg-config libboost-program-options-dev libcodec2-dev libprotobuf-dev \
      protobuf-compiler dh-make-golang dh-golang golang-any golang-github-hashicorp-logutils-dev libsamplerate0-dev \
      libicu-dev libudev-dev gfortran libboost-dev libcurl4-openssl-dev libbladerf-dev libhackrf-dev liblimesuite-dev \
      libncurses5-dev lighttpd libliquid-dev libglib2.0-dev libconfig++-dev zlib1g-dev libxml2-dev libjansson-dev \
      libairspyhf-dev libhidapi-dev libiio-dev libad9361-dev xxd qt5-qmake qtbase5-dev libpuse-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN git config --global user.name "OpenWebRX Jenkins" && \
    git config --global user.email "jenkins@openwebrx.de"

ADD docker/scripts/build-all.sh /

ADD packages /packages

ENTRYPOINT [ "/build-all.sh" ]