ARG BASE
FROM $BASE

ENV DEBIAN_FRONTEND=noninteractive

RUN echo 'Acquire::Retries "3";' > /etc/apt/apt.conf.d/80-retries && \
    apt-get update && \
    apt-get install --no-upgrade -y wget gnupg apt-transport-https && \
    wget -O - https://repo.openwebrx.de/debian/key.gpg.txt | apt-key add && \
    if grep -q "Ubuntu" /etc/os-release; then \
        echo "deb https://repo.openwebrx.de/ubuntu/ hirsute main" > /etc/apt/sources.list.d/openwebrx.list && \
        echo "deb https://repo.openwebrx.de/ubuntu/ unstable main" > /etc/apt/sources.list.d/openwebrx-unstable.list; \
    else \
        echo "deb https://repo.openwebrx.de/debian/ bullseye main" > /etc/apt/sources.list.d/openwebrx.list && \
        echo "deb https://repo.openwebrx.de/debian/ experimental main" > /etc/apt/sources.list.d/openwebrx-experimental.list; \
    fi && \
    apt-get update && \
    apt-get install --no-upgrade -y cmake build-essential debsigs git devscripts dh-python python3-all \
      python3-setuptools libpython3-dev libfftw3-dev librtlsdr-dev libsoapysdr-dev soapysdr-tools netcat \
      git-buildpackage libitpp-dev libsndfile1-dev portaudio19-dev help2man pkg-config libboost-program-options-dev \
      libcodec2-dev libprotobuf-dev protobuf-compiler dh-make-golang dh-golang golang-any \
      golang-github-hashicorp-logutils-dev libsamplerate0-dev libicu-dev libudev-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN git config --global user.name "OpenWebRX Jenkins" && \
    git config --global user.email "jenkins@openwebrx.de"

ADD docker/scripts/build-all.sh /

ADD packages /packages

ENTRYPOINT [ "/build-all.sh" ]