ARG STABLE_TAG
FROM 768356633999.dkr.ecr.eu-central-1.amazonaws.com/package-builder:$STABLE_TAG

RUN if grep -q "Ubuntu" /etc/os-release; then \
        echo "deb https://repo.openwebrx.de/ubuntu/ unstable main" > /etc/apt/sources.list.d/openwebrx-unstable.list; \
    else \
        echo "deb https://repo.openwebrx.de/debian/ experimental main" > /etc/apt/sources.list.d/openwebrx-experimental.list; \
    fi && \
